dataset:
  repo_id: keyturning_pi0 # Repository ID
  root: /root/autodl-tmp/ur5_rg2_real_smolvla_dataset_force_keyturning # Your root for data file!
policy:
  type : pi0
  chunk_size: 2
  n_action_steps: 2
  
save_checkpoint: true
output_dir: /root/autodl-tmp/checkpoints_pi0_keyturning # Save directory
batch_size: 8
job_name : pi0_keyturning
resume: false 
seed : 42
num_workers: 2
steps: 20_000
eval_freq: -1 # No evaluation
log_freq: 50
save_checkpoint: true
save_freq: 10_000
use_policy_training_preset: true
  
wandb:
  enable: False
  project: pi0_keyturning
  entity: <your_wandb_entity>
  disable_artifact: true